### PR TITLE
Update finding_list_0x6d69636b_user.csv

### PR DESCRIPTION
**Pull request by rafalfitt**
this is a computer policy, not a user policy

please note class="Machine" in WPN.admx:57 :
<policy name="NoCloudNotification" class="Machine" displayName="$(string.NoCloudNotification)" explainText="$(string.NoCloudNotificationExplain)"  key="SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications" valueName="NoCloudApplicationNotification">

### CODE REVIEW

**Comment by 0x6d69636b** [comment]
I disagree, it is also a User policy, see on Windows 10 21H2
image

**Comment by rafalfitt** [comment]
my mistake: this is a machine policy
4000,"Administrative Templates: Start Menu and Taskbar","Notifications: Turn off notifications network usage",Registry,,HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion,NoCloudApplicationNotification,,,,0,1,=,Medium

**Comment by rafalfitt** [comment]
https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.Notifications::NoCloudNotification

**Comment by 0x6d69636b** [comment]
You're right, it is fixed in commit https://github.com/0x6d69636b/windows_hardening/commit/918218fbd6c5ae856e2a9d8bbc01809d676dcd79

**Pull request closed without merging**
