### PR TITLE
Update finding_list_0x6d69636b_user.csv

### PR DESCRIPTION
**Pull request by rafalfitt**
please check the latest onent16.admx:1001

### CODE REVIEW

**Comment by 0x6d69636b** [comment]
As this setting is part of the recommendations of Will Dormann (see https://gist.githubusercontent.com/wdormann/732bb88d9b5dd5a66c9f1e1498f31a1b/raw/69c9d9d14b386d8f178e59a046804501ec1ee304/disable_ddeauto.reg) it is fine by me to set it directly and not in the policies tree

**Comment by rafalfitt** [comment]
what is the source of this recommendations? Any documentation for these settings?

**Comment by 0x6d69636b** [comment]
This was around fall 2017 were new DDE based attacks arise, see one tweet from Will mentioning his recommendations: https://twitter.com/wdormann/status/922438547642241024

**Comment by rafalfitt** [comment]
you are right, this is Office 2019-2016 stuff:
https://docs.microsoft.com/en-us/security-updates/securityadvisories/2017/4053440
https://docs.microsoft.com/en-us/office/troubleshoot/settings/how-to-securely-open-office-documents-that-have-dde-fields

**Pull request closed without merging**
