### PR TITLE
Turn script into module

### PR DESCRIPTION
**Pull request by BZanten**
After installing this module in the default 'Modules' folder, for system-wide this would be:
C:\Program Files\WindowsPowerShell\Modules\HardeningKitty\<Version>\   folder

The new way to import the module and use the command will be

```
Import-Module HardeningKitty
Invoke-HardeningKitty
```

### CODE REVIEW

**Review by 0x6d69636b — APPROVED** [review]
Looks good! I'll update the definition file outside of this PR

**Comment by BZanten** [comment]
Nice Michael !

Please note that you may need to update some documentation on your website…

The old way to start the script, was to dot-source the script, then run the function within:

. .\Invoke-HardeningKitty.ps1
Invoke-HardeningKitty

Now the new way to start is, to import-module first.
If the module is (later) installed via a Repository like PSRepository, it is normally installed in a path mentioned in $env:PSModulePath
And can be called like this:

Import-Module HardeningKitty
Invoke-HardeningKitty

For now, if people download the new module(s) from the website, they should use:

Import-Module <path>\HardeningKitty.psd1
Invoke-HardeningKitty

Regards, Ben van Zanten

**Comment by 0x6d69636b** [comment]
Hi Ben, I updated the README this weekend ;-) Did you spot any improvements?

**Comment by BZanten** [comment]
Oops forgot to read that one, it is fine !
Good work, thx.

**Pull request merged**
