### PR TITLE
Update finding_list_msft_security_baseline_windows_11_23h2_machine.csv

### PR DESCRIPTION
**Pull request by onePrometheus**
Change recommended value 3 to 0, because it's the most secure.
https://admx.help/?Category=Windows_10_2016&Policy=FullArmor.Policies.0EF0F32B_7305_4FC7_BBEB_D43DCC622C81::POL_DriverLoadPolicy_Name

image

### CODE REVIEW

**Comment by Harvester57** [comment]
Correct value should be 8, not 0, if you want to enable the "Good only" mode.

**Comment by Harvester57** [comment]
And you should probably propose this change in the following file https://github.com/0x6d69636b/windows_hardening/blob/master/lists/finding_list_0x6d69636b_machine.csv, not in the one implementing the Microsoft baseline, this one is not up to interpretation on what setting is more secure or not, it's only the raw implementation of what Microsoft is publishing.

**Comment by 0x6d69636b** [comment]
As @Harvester57 said, this list represents Microsoft's best practices. I'm not going to change any settings here

**Comment by onePrometheus** [comment]
> Correct value should be 8, not 0, if you want to enable the "Good only" mode.

Yes you're right
I noticed it quickly between two activities and sent too quickly. Thanks for the correction

**Comment by onePrometheus** [comment]
> As @Harvester57 said, this list represents Microsoft's best practices. I'm not going to change any settings here

Ok that's understandable 

I also have my own version with recommended values for my environnement. I find it surprising that the security baseline allows malicious elements.
Also, I hadn't quite understood how this repo works. Sorry about that.

**Comment by 0x6d69636b** [comment]
No worries. If you like, you can add your own list to the repository

**Pull request closed without merging**
