### PR TITLE
Implement "secedit" in HailMary mode

### PR DESCRIPTION
**Pull request by GlennMatthys**

### CODE REVIEW

**Review by 0x6d69636b — COMMENTED** [review]
You used in the pull request #18 a Switch for the "areas" parameter. Do we also need this in this function, or is the areas parameters always "SECURITYPOLICY" anyway?

**Comment by GlennMatthys** [comment]
In the case I need, the CIS benchmarks, only after implementing I noticed that it's only used for "Account Policies". But I left the area switch in place for future expansion. But yes at this time it's unneccessary. So remove it then?

**Comment by 0x6d69636b** [comment]
I suggest we use the area switch in both cases, then we are already prepared for any additional uses

**Comment by GlennMatthys** [comment]
Have a look at this.

**Review by 0x6d69636b — APPROVED** [review]

**Comment by 0x6d69636b** [comment]
Looks good to me, thanks again!

**Pull request merged**
