### PR TITLE
Adding more informations about commands

### PR DESCRIPTION
**Pull request by ataumo**

### CODE REVIEW

**Review by 0x6d69636b — CHANGES_REQUESTED** [review]
I like the approach of expanding the documentation and including more examples in the README. But I think the structure with the question form is not ideal. It is better to create a subchapter Examples and then include the examples. Then we can also take the examples from the PowerShell script. We should also introduce several parameters. Do you want to edit your proposal? Otherwise, I can also take your input and implement my structure.

**Comment by ataumo** [comment]
Okay ! I let you to implement your structure with this approach.

**Comment by 0x6d69636b** [comment]
Alright, I added some examples. Feel free to add corrections/additions here :-)

**Comment by ataumo** [comment]
Good ! It's more simple like that ! 👍

**Comment by 0x6d69636b** [comment]
Great, then I'll close the pull request. Thanks for the inspiration :-)

**Pull request closed without merging**
