### PR TITLE
Adding Min PIN Length (1663)

### PR DESCRIPTION
**Pull request by ataumo**
More information about this policy : https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.VolumeEncryption::MinimumPINLength_Name

### CODE REVIEW

**Comment by 0x6d69636b** [comment]
With Windows 10, version 1703, the minimum length for the BitLocker PIN was increased to 6 characters (see [docs.microsoft.com](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings#configure-minimum-pin-length-for-startup)). Therefore this setting has no additional benefit. I checked the database and found that only DoD/Stig requires a minimum length (also 6 characters), all others have no recommendation for this. No the questions is, would you recommend a higher value like 8 or 10? The maximum number is 20.

**Comment by ataumo** [comment]
Yes I know, but it can be modify to apply you own value. For example, if you apply HailMary on you computer and you want a higher value like 8 or 10, you can do that through this policy in the CSV file. 

I really like your work and I think it's a very good way to harden an OS. I want to make its use more accessible.
For your information, I'm working on a HardeningKitty Interface to use more easily your work. This interface give you more informations about policies and allows you to generate a CSV file for the purpose of auditing or applying a configuration.

Like that :
Capture d’écran 2021-06-25 à 17 49 07

Capture d’écran 2021-06-25 à 17 59 11

**Comment by 0x6d69636b** [comment]
Wow, incroyable! :1st_place_medal: I'm speechless, this looks really cool. Could you please open a discussion and share more of your work there? Then more people can see your work. 

Now, back to business. I get your point. In my checklist, I try to raise the bar with my recommendation, implement security recommendation early and maybe use stricter settings than other guidelines. Therefore I won't settle with the default value in that case. But security is always a tradeoff, so I'm not sure if we should go to 8, 10 or even more. As it's your pull request, I'm asking for your opinion, where should we start? :-)

**Comment by ataumo** [comment]
Merci beaucoup ! I'm waiting to get the okay from my organisation to publish it. ;-)

Indeed, I’m careful about the compromise security/uses. As you can see in the interface, I identify each policy with UIX impact tags (Impact, potentially, no impact) to distinguish if it is too restrictive for the user.
And about this policy, I think 8 is a bit high value but it's reasonable.

**Review by 0x6d69636b — CHANGES_REQUESTED** [review]
As discussed, could you please increase the value to 8? Thank you

**Review by 0x6d69636b — APPROVED** [review]

**Comment by 0x6d69636b** [comment]
Oh damn, there is a mix-up with the ID, Text and registry. The ID and text is not correct for BitLocker, I'll fix that right now

**Comment by ataumo** [comment]
Which id are you talking about ?

**Comment by 0x6d69636b** [comment]
You chose the ID 1663 for the finding, but the BitLocker findings are around 17xx, therefore I changed the ID to 1763 (https://github.com/0x6d69636b/windows_hardening/commit/8426050c46ab0cf86000f2f57e40109c0507be22)

**Comment by ataumo** [comment]
Ah yes sorry, indeed it was a mistake ! Thank you ;-)

**Comment by ataumo** [comment]
Hello, my project is finally published : https://github.com/ataumo/windows_hardening_interface

**Comment by 0x6d69636b** [comment]
Brilliant work! :+1: I added a section for your project in the README

**Pull request merged**
